server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动名称
    url: jdbc:mysql://117.72.89.234:13306/ai_traffic
    username: root
    password: 456123
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhangbt.domain.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
at:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: com-zhangbt-secure-secret-key-sporejwt-b8b6
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token
